spring.datasource.url=jdbc:mysql://coffeehut.c5c4guwiid9k.eu-west-2.rds.amazonaws.com:3306/coffee_hut?createDatabaseIfNotExist=true
spring.datasource.username=admin
spring.datasource.password=CoffeeHut2026!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
spring.main.allow-bean-definition-overriding=true
